# Generated by Django 4.1.4 on 2023-01-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
