# Generated by Django 4.1.4 on 2023-01-09 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_category_auction_listings_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='user_id',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
