# Generated by Django 4.1.4 on 2023-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_auction_listings_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='price',
            field=models.FloatField(max_length=8),
        ),
    ]
