# Generated by Django 4.1.4 on 2023-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
